---
- name: Delete DNS record at GCP
  gcp_dns_resource_record_set:
    name: "{{ item }}.{{ pd_public_domain }}."
    managed_zone:
      name: "{{ gcp_managed_zone_name }}"
      dnsName: "{{ gcp_managed_zone_domain }}"
    type: A
    ttl: 120
    target:
      - "{{ pd_public_ip }}"
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_serviceaccount_file }}"
    state: absent
  with_items:
    - api
    - '*.apps'

- name: Delete IPv6 DNS record at GCP
  gcp_dns_resource_record_set:
    name: "{{ item }}.{{ pd_public_domain }}."
    managed_zone:
      name: "{{ gcp_managed_zone_name }}"
      dnsName: "{{ gcp_managed_zone_domain }}"
    type: AAAA
    ttl: 120
    target:
      - "{{ pd_public_ipv6 }}"
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_serviceaccount_file }}"
    state: absent
  with_items:
    - api
    - '*.apps'
  when: (pd_public_ipv6 is defined) and (pd_public_ipv6|length > 0)
