#!/usr/bin/env ansible-playbook
---
# If you like to play: ./ansible/create.yml --skip-tags public_dns,letsencrypt
- hosts: localhost
  connection: local
  # gather_facts true because we need the public ip address
  gather_facts: true
  vars_files:
    - ../cluster.yml

  tasks:
    - name: Start cluster
      import_role:
        name: openshift-4-cluster
        tasks_from: start.yml
