#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars_files:
  - ../cluster.yml
  tasks:

  - import_role:
      name: openshift-4-cluster
      tasks_from: certificate-renewal.yml
    when: letsencrypt_disabled == false
  - import_role:
      name: openshift-4-cluster
      tasks_from: certificate-install.yml
    when: letsencrypt_disabled == false
